# Generated by Django 3.0.5 on 2020-09-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningModel',
        ),
    ]
