# Generated by Django 3.0.5 on 2020-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='robot',
            name='robot_data',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
