# Generated by Django 3.0.5 on 2020-08-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20200831_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='name',
        ),
    ]
