# Generated by Django 3.0.5 on 2020-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_remove_robot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_data',
            field=models.TextField(default=''),
        ),
    ]
